# Generated by Django 5.0.1 on 2024-01-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_menucategory_menucard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucard',
            name='cartegory_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='category_name', to='demoapp.menucategory'),
        ),
    ]
