# Generated by Django 5.0.1 on 2024-01-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_author_book_bookcopymodel_genre_member_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(unique=True),
        ),
    ]
